In [1]:
#numpy import
import numpy as np

In [5]:
# ndarray 생성하기
arr = np.array([1,2,3,4], dtype=int)

In [6]:
arr

array([1, 2, 3, 4])

In [8]:
type(arr)

numpy.ndarray

In [10]:
mylist1 = [1,2,3,4]

In [11]:
mylist2 = [[1,2,3,4],[5,6,7,8]]

In [12]:
arr1 = np.array(mylist1)

In [13]:
arr2 = np.array(mylist2)

In [15]:
#shape 확인하기
arr1.shape

(4,)

In [16]:
arr2.shape

(2, 4)

In [17]:
# array에서 data 타입
# 파이썬 list에서는 여러 데이터 타입 사용가능,
#array에서는 단일 데이터 타입만 허용
mylist = [1, 3.14, '테스트', '1000']

In [18]:
mylist

[1, 3.14, '테스트', '1000']

In [19]:
mylist[1]

3.14

In [20]:
mylist[2]

'테스트'

In [21]:
# int와 float 혼재
arr = np.array([1,2,3,3.14])

In [22]:
#전부 float형으로 변환
arr

array([1.  , 2.  , 3.  , 3.14])

In [23]:
arr = np.array([1,2,3,3.14], dtype = int)

In [24]:
arr

array([1, 2, 3, 3])

In [25]:
# int와 str 타입이 혼재
arr = np.array([1,3.14,'테스트','1000'], dtype=int)

ValueError: ignored

In [26]:
arr = np.array([1,3.14,'1000'], dtype=int)

In [27]:
arr

array([   1,    3, 1000])

###슬라이싱(Slicing)

In [28]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [29]:
arr.shape

(10,)

In [32]:
# 인덱스
arr[0]

0

In [31]:
arr[5]

5

In [33]:
arr[10]

IndexError: ignored

In [34]:
arr[-1]

9

In [35]:
arr[-10]

0

In [36]:
# 2차원 array
arr2d = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

In [37]:
arr2d.shape

(3, 4)

In [38]:
# arr2d[행, 열]
arr2d[0,2]

3

In [39]:
arr2d[2,1]

10

In [40]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[:5]

array([0, 1, 2, 3, 4])

In [43]:
arr[1:5]

array([1, 2, 3, 4])

In [44]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
# 열은 처음부터 끝까지 행은 0행을 가져오기
arr2d[0, :]

array([1, 2, 3, 4])

In [49]:
arr2d[:, 2]

array([ 3,  7, 11])

In [51]:
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
arr2d[:2, 2:]

array([[3, 4],
       [7, 8]])

In [53]:
# Fancy 인덱싱 : 범위가 아닌 특정 index의 집합의 값을 선택하여 추출할 때 사용

In [54]:
arr = np.array([10,22,2,33,44,55,6,66,64])

In [56]:
# [추출하고 싶은 인덱스] 대괄호로 묶어준다.
arr[[1,3,5]]

array([22, 33, 55])

In [57]:
idx = [1,3,5]

In [58]:
arr[idx]

array([22, 33, 55])

In [59]:
# 2차원배열 적용하기
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
arr2d[[0,1], :] # 0,1번째 행과 모든열 가져오기

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [63]:
arr2d[:, [1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [64]:
# Boolean 인덱싱
arr = np.array([1,2,3,4,5,6,7])

In [65]:
myTF = [True,False,True]

In [66]:
arr[myTF] # 원소의 갯수가 일치하지 않음

IndexError: ignored

In [67]:
myTF = [True, False, True,False,False,True,False]

In [69]:
arr[myTF]

array([1, 3, 6])

In [71]:
# 조건 연산자를 활용한 필터링
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
arr2d>2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [74]:
# arr2d[조건필터] : True 조건만 추출
arr2d[arr2d>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
arr2d[arr2d<5]

array([1, 2, 3, 4])

In [76]:
# arange
arr = [1,2,3,4,5,6,7,8,9,10]

In [77]:
arr = np.arange(1,11)

In [78]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr = np.arange(start=1, stop=11)

In [80]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr = np.arange(stop=11, start=3)

In [82]:
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
# 홀수값만 가져오기
arr = np.arange(stop=11, start=1, step = 2)

In [84]:
arr

array([1, 3, 5, 7, 9])

In [87]:
arr = np.arange(1, 11, 2)

In [88]:
arr

array([1, 3, 5, 7, 9])

In [89]:
arr = np.arange(1,21)

In [90]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [91]:
for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [93]:
#1차원 정렬
arr = np.arange(1,11)

In [94]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr = np.array([1,10,5,3,7,8,9,4,2])

In [96]:
np.sort(arr)# 오름차순 정렬

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10])

In [97]:
np.sort(arr)[::-1]# 내림차순 정렬

array([10,  9,  8,  7,  5,  4,  3,  2,  1])

In [98]:
arr

array([ 1, 10,  5,  3,  7,  8,  9,  4,  2])

In [99]:
arr.sort()# arr이 정렬된 상태로 유지됨.

In [100]:
arr

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10])

In [101]:
#N차원 정렬
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
arr2d = np.array([[5,6,7,8],
                      [4,3,2,1],
                      [10,9,12,11]])

In [103]:
#열정렬
np.sort(arr2d, axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [106]:
#행정렬
np.sort(arr2d, axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [107]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [108]:
#index를 반환하는 argsort
# 정렬된 값을 반환하는 것이 아니라 index를 반환한다.(정렬된 값의 인덱스를 반환)
np.argsort(arr2d, axis=1)# 값은 변하는데 인덱스는 변하지 않을 때 활용

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]])

In [109]:
np.argsort(arr2d, axis=0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]])

In [111]:
# 행렬 - 덧셈
a = np.array([[1,2,3],
                [2,3,4]])

In [112]:
b = np.array([[3,4,5],
                [1,2,3]])

In [113]:
a + b

array([[4, 6, 8],
       [3, 5, 7]])

In [114]:
a -b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [115]:
# sum
np.sum(a, axis=0)

array([3, 5, 7])

In [116]:
np.sum(a,axis=1)

array([6, 9])

In [117]:
a.shape, b.shape

((2, 3), (2, 3))

In [118]:
#단순 곱셈
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

In [119]:
# 행렬 곱(dot product) : 단순 곱셈과는 다르다.
a = np.array([[1,2,3],
                [2,3,4]])

In [120]:
b = np.array([[1,2],
                  [3,4],
                  [5,6]])

In [121]:
a.shape, b.shape

((2, 3), (3, 2))

In [122]:
np.dot(a, b)

array([[22, 28],
       [31, 40]])

In [123]:
a = np.array([[1,2,3],
                [2,3,4],
              [1,2,3]])

In [124]:
a.shape, b.shape

((3, 3), (3, 2))

In [125]:
np.dot(a,b)

array([[22, 28],
       [31, 40],
       [22, 28]])

In [126]:
a.dot(b)

array([[22, 28],
       [31, 40],
       [22, 28]])

In [127]:
# 브로드캐스팅(Broadcasting)
a = np.array([[1,2,3],
                [2,3,4]])

In [128]:
b = np.array([[3,3,3],
                  3,3,3]])

In [129]:
a + b

array([[4, 5, 6],
       [5, 6, 7]])

In [130]:
a+ 3 #Broadcasting 방식

array([[4, 5, 6],
       [5, 6, 7]])

In [132]:
a-3

array([[-2, -1,  0],
       [-1,  0,  1]])